version: '3.2'
services:
  pcic-react-leaflet-components-demo:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    image: pcic/pcic-react-leaflet-components-demo
    container_name: pcic-react-leaflet-components-demo
    ports:
      - "30111:3000"

networks:
  default:
    external:
      name: pcicbr0
